# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-17 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
