# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quem_Somos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maximi/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Descrição',
                'verbose_name_plural': 'Descrições',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Maxpro',
        ),
    ]
