# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxmi', '0002_auto_20190507_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='midia/portifolio', verbose_name='Imagem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='quem_somos',
            options={'ordering': ['title'], 'verbose_name': 'Descrição/Foto', 'verbose_name_plural': 'Descrições/Fotos'},
        ),
        migrations.AlterField(
            model_name='quem_somos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='midia/quem_somos', verbose_name='Imagem'),
        ),
    ]
