# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxmi', '0003_auto_20190507_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='midia/servicos', verbose_name='Imagem')),
                ('brevedescri', models.CharField(max_length=200, verbose_name='Breve Descrição')),
                ('completdescri', models.TextField(blank=True, verbose_name='Descrição Completa')),
            ],
            options={
                'verbose_name': 'Seriviço',
                'verbose_name_plural': 'Seriviços',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='portifolio',
            options={'ordering': ['title'], 'verbose_name': 'Portifolio', 'verbose_name_plural': 'Portifolio'},
        ),
        migrations.AlterModelOptions(
            name='quem_somos',
            options={'ordering': ['title'], 'verbose_name': 'Descrição/Foto', 'verbose_name_plural': 'Quem Somos'},
        ),
    ]
